# Generated by Django 6.0.6 on 2026-06-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_seed_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='stock_quantity',
        ),
    ]
